### ISSUE TITLE
Program needs more ways to close gracefully

### ISSUE THREAD

**Issue by BlueNalgene** [jonas-koeritz/actioncam#2]
Actioncam does not have a way to close gracefully.  On my implementation, I start the RTSP server, then run a Python program.  When the Python program closes with an exception or through a KILL command, Actioncam remains running.  If I start another Python program with Actioncam still running in the background, I get the error message:
```
2019/10/02 16:53:02 ERROR: dial tcp 192.168.100.1:6666: connect: no route to host
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x617a38]
 
goroutine 1 [running]:
github.com/jonas-koeritz/actioncam/libipcamera.(*Camera).SendPacket(0x44201060e0, 0x4420136000, 0x88, 0x100, 0x4420136000, 0x88)
    /home/odroid/go/src/github.com/jonas-koeritz/actioncam/libipcamera/Camera.go:297 +0x20
github.com/jonas-koeritz/actioncam/libipcamera.(*Camera).Login(0x44201060e0, 0x44201060e0, 0x10)
    /home/odroid/go/src/github.com/jonas-koeritz/actioncam/libipcamera/Camera.go:107 +0x1ac
main.connectAndLogin(0x442001a660, 0x10, 0x10, 0x1a0a, 0x73d5fd, 0x5, 0x73d512, 0x5, 0x44200a5900, 0x442004cd50)
    /home/odroid/go/src/github.com/jonas-koeritz/actioncam/actioncam.go:26 +0xd8
main.main.func23(0x44200a5900, 0x442004cd50, 0x1, 0x1)
    /home/odroid/go/src/github.com/jonas-koeritz/actioncam/actioncam.go:247 +0x158
github.com/spf13/cobra.(*Command).execute(0x44200a5900, 0x442004cd10, 0x1, 0x1, 0x44200a5900, 0x442004cd10)
    /home/odroid/go/src/github.com/spf13/cobra/command.go:822 +0x364
github.com/spf13/cobra.(*Command).ExecuteC(0x44200a4780, 0x6ee7e0, 0x44200a4c80, 0x442004ccb0)
    /home/odroid/go/src/github.com/spf13/cobra/command.go:917 +0x204
github.com/spf13/cobra.(*Command).Execute(0x44200a4780, 0x442005bc18, 0x1)
    /home/odroid/go/src/github.com/spf13/cobra/command.go:867 +0x20
main.main()
    /home/odroid/go/src/github.com/jonas-koeritz/actioncam/actioncam.go:327 +0x1470
```

If I force Actioncam to close with a `ctrl`+`c` interrupt, it fails to shut down properly and does not release all resources, resulting in a similar resource related segfault.  This problem could be solved by always closing gracefully (see [here](https://guzalexander.com/2017/05/31/gracefully-exit-server-in-go.html)) or minimized by giving the RTSP server a "daemonic" shutdown command.

**Comment by jonas-koeritz** [comment]
I will implement an overall solution  for stopping the client gracefully.
